### ISSUE TITLE
does it actually create a file?

### ISSUE THREAD

**Issue by aryairani** [1arp/create-a-file-action#2]
Hi, it's my first time using the plugin, so I am probably doing something wrong.

I have:

````
Run 1arp/create-a-file-action@0.3
  with:
    path: /home/runner/work/_temp
    file: setup-jit.md
    content: |
      blah blah
````

But when I `ls /home/runner/work/_temp`, I don't have a `setup-jit.md`.

**Comment by 1arp** [comment]
Hi, I would point you to the  [README](https://github.com/1arp/create-a-file-action/blob/master/README.md).

The actions are usually run in jobs.

You can not just run the action isolated, it needs to run on a container ( abstracted away by Github ) in jobs. 
[JOBS](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on)

Since you are not defining an action you have to also use the `uses` parameter where you can define the action to be used.

```yaml
jobs:
  createFile:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # used to checkout the git repo in the container
      - uses: 1arp/create-a-file-action@0.3
        with:
          path: 'src'
          file: 'foo.bar'
          content: |
            Hello
            World
```

More info about workflows: [About workflows](https://docs.github.com/en/actions/using-workflows/about-workflows)

**Comment by aryairani** [comment]
Thank you, yes my excerpt above wasn't the workflow YAML, it was the log output from my job, which included the `with` block which I figured was the relevant piece.

**Comment by 1arp** [comment]
I see. The action appends the path provided to the current working directory, but what I see is you want to provide an absolute path, which is not supported yet. If not it should work as expected.
But an absolute path is a valid use case. I will try to support it by the end of the month.

**Comment by aryairani** [comment]
Ok thanks for the confirmation!

**Comment by 1arp** [comment]
This should be fixed with the latest 0.4.4 release.
But there is a caveat, the user must have permissions to write to the path.

If you want to specify root user, you can use something like: 

```yaml
 createFile:
    name: Create A File Test
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: 1arp/create-a-file-action@0.4.4
        with:
          path: '/home'
          isAbsolutePath: true
          file: 'foo.bar'
          content: |
            Hello
            World
```
