### ISSUE TITLE
Workflow that worked with v0.3 but does not with v0.4

### ISSUE THREAD

**Issue by tueda** [1arp/create-a-file-action#5]
The following usage of the action does not work with 0.4.2 [(log)](https://github.com/tueda/test-create-a-file-action/actions/runs/8567670337) or 0.4.4 [(log)](https://github.com/tueda/test-create-a-file-action/actions/runs/8567672829):
```yaml
      - uses: 1arp/create-a-file-action@0.4.4
        with:
          file: foo.txt
          content: |
            Hello
            World
```
```
Error: ENOENT: no such file or directory, mkdir ''
```
Indeed, with 0.3 [(log)](https://github.com/tueda/test-create-a-file-action/actions/runs/8567663637), this successfully creates `foo.txt` in the root of the repository directory.
